<?php
function proventamessage_form_privatemsg_new_alter(&$form, &$form_state) {
    //dsm($form);
    $u = $_GET['uid'];
   
  $form['recipient']['#default_value'] =$u;
  // Check if a default value is configured for the to field.
//  if (!empty($form['privatemsg']['recipient']['#default_value'])) {
// 
//    // Display a visible markup element.
//    $form['privatemsg']['recipient_display'] = array(
//      '#value' => t('To: @recipients', array('@recipients' => $form['privatemsg']['recipient']['#default_value'])),
//      '#weight' => -10,
//    );
//
//   
//// Convert the recipient field to a value type and force the default value.
//    $form['privatemsg']['recipient']['#type'] = 'value';
//    $form['privatemsg']['recipient']['#value'] = 'richa(6)';
//  }
//    dsm($form);
    

  }

?>