<?php
function proventafriendsearch_form_alter(&$form, &$form_state, $form_id){
if($form['#form_id'] == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-freiend-search-page')
    {
        //dsm($form);
        $form['uid_raw']['#attributes'] = array('placeholder' => t('Friend Search'));
    $form['uid_raw']['#autocomplete_path'] = 'autocomplete_search_friends';    
    $form['uid_raw']['#attributes']['class'][] = 'form-autocomplete';

       
}
}

/**
* Implementation of hook_menu().
*/

function proventafriendsearch_menu() {
 
    $items['autocomplete_search_friends'] = array(
    'page callback' => 'autocomplete_search_friend',
    'access arguments' => array('access content'),
  );
  return $items;
}

function autocomplete_search_friend($string){
   
 $string = array(':s' => $string . '%');    
  $result = db_query('SELECT * FROM `users` WHERE name  LIKE :s', $string); 
$items = array();
foreach ($result as $location) {   
$link = drupal_get_path_alias('user/'.$location->uid);
$items[$location->name] = "<a class='friend-autocomplete' href='/$link'>".$location->name."</a>";
}

  print drupal_json_encode($items);
  //dsm($items);
}
    
?>